![imagen](./img/ejercicios.png)

In [1]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
my_array = np.arange(10)
print(my_array)

print(my_array[10:0:-2])




[0 1 2 3 4 5 6 7 8 9]
[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [15]:
print(my_array[8:6:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [19]:
print(my_array[3:0:-1])

[3 2 1]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [41]:
array_1 = np.arange(1,21).reshape(4,5)
print(array_1)

array_1i = array_1[::-1,::-1]
print(array_1i)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [49]:
print(array_1[0:2,0:2])

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [50]:
array_2=array_1[::2, ::2]

print(array_2)


[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [56]:
array_3= array_1[:3:,::-1]
print(array_3)

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [ ]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
loro = x =="Loro"
print(x[loro])

Loro = np.where(x == "Loro")
print(x[Loro])



['Loro' 'Loro']
['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [8]:
x= np.arange(20)
print(x)

x1,x2 = np.split(x,2)
print(x1.reshape(5,2))
print(x2.reshape(5,2))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [11]:
mi_array_10 = np.zeros(10)

print(mi_array_10)
print(mi_array_10.nbytes)

mi_array_10[3] = 1

print(mi_array_10)
print(mi_array_10.nbytes)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
80
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
80


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [13]:
v1 = np.arange(10,50)
print(v1)

v1[::-1]

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [25]:
v2= np.array([1,2,0,0,4,0])

print(v2.nonzero())

def indices_n0(array):
    return np.nonzero(array)[0]


(array([0, 1, 4]),)


In [26]:
indices_n0(v2)

array([0, 1, 4])

## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [53]:
np.random.seed(567)

matriz_random = np.random.randint(10,500,(10,10))

print(matriz_random)

print(matriz_random.min())
print(matriz_random.max())

[[382 205 288  54 143 403  26  54 456 299]
 [340  82 292 383 131 178  59  88  15 107]
 [175 164 449 155  99 428 384 247 284 300]
 [ 88 152 439  69 474 220 271 382  86 145]
 [358 211 346  37 147 119  44 292 440 109]
 [ 74 199  95 348 308  71 475 309  72 235]
 [143 183 321 150 260 117 278 223 208 330]
 [291 352 258 374 205 438 443 382 347 124]
 [325 138 493 180  84 229  19 274 306  88]
 [ 17 380 393 187 315 167 187  64 302  91]]
15
493


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [52]:
matriz_random_2 = np.random.randint(10,400,30)

print(matriz_random_2)
print(matriz_random_2.mean())

[ 28 225 360  57 204 328 137 247 125  98  47 378 280 208 208 277 226 142
 337 268  36 254 159 120 195 217 103 221 341  56]
196.06666666666666


## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [46]:
array_sq = np.ones((5,5), dtype=int)
print(array_sq)

array_sq[1:-1, 1:-1] = 0   
print(array_sq)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [49]:
array_8 = (np.indices((8, 8)).sum(axis=0)) % 2

print(array_8)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [51]:
array_tile = np.array([[0,1],[1,0]])

tablerito = np.tile(array_tile, (4,4))
print(tablerito)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [ ]:
matriz_random_3 = np.random.randint(40,600,(5,5))

media = np.mean(matriz_random_3)
st_dev = np.std(matriz_random_3)

normalizar = ((matriz_random_3 - media)/ desviacion)

print(normalizar)

[[ 0.21106861 -1.35169957 -0.52919     1.69158584  0.35658953]
 [ 1.14746412  1.50810293 -1.35802657  0.0402397  -1.55416347]
 [ 0.83744128 -0.69369192 -0.93411779 -0.02303027 -1.47823951]
 [ 1.01459719 -0.3393801  -0.05466525 -1.63008743  0.85009528]
 [ 0.37557052  0.55272643 -0.75063489  1.05888617  1.05255917]]


## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [62]:
secuencia = np.arange(0,11)
print(secuencia)

valor_1 = secuencia.copy()

valor_1[(valor_1 >= 3) & (valor_1 <=8)] = -1
print(valor_1)

null = (secuencia>= 3) & (secuencia <=8)
valor_null = ~null
print(valor_null)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]
[ True  True  True False False False False False False  True  True]
